feat: 코드 리뷰 방식 변경
careersupport-org/backend-legacy pull request #6
Opened 2024-11-05 10:36 UTC by YeaChan05

## #️⃣연관된 이슈

> #5 

## 📝작업 내용

> 코드 리뷰시 이전에 리뷰를 진행했던 부분을 리뷰하지 않도록 pinpoint를 통해 변경사항을 기준으로만 리뷰하도록 로직 변경

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 실제 애플리케이션 구동으로 검증하지 않았기에 일부 문제가 있는 코드가 있을 수 있습니다. 면밀히 확인 부탁드립니다.

2024-11-06 02:16 UTC, minturtle requested changes
고생하셨습니다!

2024-11-06 02:16 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/entity/CommitPinpoint.java
> +    private String sha;
sha가 가장 최근 커밋의 sha를 의미하는 거라면, lastSha와 같이 이름을 더 잘드러나게하는건 어떨까요?

2024-11-06 02:16 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/respository/ReviewPinpointRepository.java
> +    Mono<CommitPinpoint> findByPrNumber(Integer prNumber);
Pr Number가 Unique한지 궁금합니다! 만약 깃헙 리포지토리가 2개가 있고, 두 개의 리포지토리가 모두 #2번의 PR을 가진다면 어떻게 되나요??

2024-11-06 02:16 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/respository/ReviewPinpointRepository.java
> +    Mono<CommitPinpoint> findByPrNumber(Integer prNumber);
만약 PR Number가 Unique하다면 prNumber을 @Indexed(unique= true) 로 구분해주면 더 좋을거같습니다

2024-11-06 02:16 UTC, minturtle commented on src/test/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewServiceTest.java
> +    ReviewPinpointRepository reviewPinpointRepository;
이거 GithubCodeReviewService가 @InjectMock이 없어서 NPE가 나더라고요. @InjectMock을 사용하던지 이전의 방식을 맞추던지 통일이 필요할거 같습니다!

2024-11-06 08:59 UTC, YeaChan05 commented on src/main/java/org/minturtle/careersupport/codereview/respository/ReviewPinpointRepository.java
> +    Mono<CommitPinpoint> findByPrNumber(Integer prNumber);
음... pr 번호 자체는 unique하지 않겠네요

조회 방식을 변경해보겠습니다

2024-11-06 08:59 UTC, YeaChan05 commented on src/main/java/org/minturtle/careersupport/codereview/entity/CommitPinpoint.java
> +    private String sha;
수정하겠습니다!

2024-11-06 09:03 UTC, YeaChan05 commented on src/main/java/org/minturtle/careersupport/codereview/respository/ReviewPinpointRepository.java
> +    Mono<CommitPinpoint> findByPrNumber(Integer prNumber);
> Pr Number가 Unique한지 궁금합니다! 만약 깃헙 리포지토리가 2개가 있고, 두 개의 리포지토리가 모두 #2번의 PR을 가진다면 어떻게 되나요??

그리고 하나의 repository에서 pr number를 unique하게 가진다고 알고 있습니다

2024-11-07 04:10 UTC, minturtle approved these changes

2024-11-07 04:11 UTC, merged